### DISCUSSION TITLE
Styling Questions

### DISCUSSION THREAD

**Discussion by MiranSeb000** [Obsidian-TTRPG-Community/fantasy-statblocks#106] [Q&A]
Hi, this is similar to the question asked about changing the colors with css but a tad different. I was curious where I would be able to find the option to remove the white shadow surrounding the stat block. I don't think it looks great with the theme I'm using and I'd like to either make it darker or remove it entirely.

**Comment by valentine195** [comment]
You have to override this bit of CSS, you’ll probably need to throw an important on there too. 

https://github.com/valentine195/obsidian-5e-statblocks/blob/f6e6c2d30f90d64b250621be645cb792debf1974/src/view/ui/Content.svelte#L315

```css
.statblock-content{
    box-shadow: <your desired shadow> !important;
}
```
