### DISCUSSION TITLE
Cyberpunk Red by @jyrogers

### DISCUSSION THREAD

**Discussion by sigrunixia** [Obsidian-TTRPG-Community/fantasy-statblocks#161] [Show and tell]
This thread is for @jyrogers and their Cyberpunk Red Statblock.

---

I created a layout for Cyberpunk Red.

![Statblock Example](https://user-images.githubusercontent.com/4572538/220460390-e9a079a4-de4c-4196-b82d-e78a6cb947da.png)

I wanted a statblock that would roll Skill Check for Players and NPCs. So each skill has a dice roll to the right that does a "STAT + Skill + 1d10" roll specific for that skill. 

In the statblock each skill has a value. They are all conditional so if there are any skills that you don't want displayed just remove the skill and the skill_check values.

Example: The Library Search Skills is represented by `library_search` . If you want Library Search displayed fill in the skill value `library_search: 7`. If you didn't want the Library Search Skill displayed then remove `library_search: from the statblock.

I've added a Death Save roll next to the Death Save value. Since the Death Save value is just the BODY STAT it is automatically generated from the `body` value in the statblock.

I haven't done any CSS or color customization. Any help with that would be appreciated.

Let me know if you have any questions or ideas for improvements.

Included in the zip file:
- JSON statblock configuration
- Example statblock markdown ( with homebrew policy disclousure )
- Example render as seen above

[Cyberpunk Red Statblock.zip](https://github.com/valentine195/fantasy-statblocks/files/10797804/Cyberpunk.Red.Statblock.zip)

FYI @felislynx-silae 

_This layout is unofficial content provided under the Homebrew Content Policy of R. Talsorian Games and is not approved or endorsed by RTG. This content references materials that are the property of R. Talsorian Games and its licensees._

---
[Cyberpunk.Red.Statblock-jyrogers.zip](https://github.com/valentine195/fantasy-statblocks/files/11218767/Cyberpunk.Red.Statblock-jyrogers.zip)

**Original Post**: https://github.com/valentine195/fantasy-statblocks/discussions/41#discussioncomment-4896485

**Comment by felislynx-silae** [comment]
@sigrunixia It is much better. Would it be possible to style it more like 
<img width="1039" alt="Zrzut ekranu 2023-04-18 o 06 50 31" src="https://user-images.githubusercontent.com/1098831/232674446-944bf00d-3711-4160-87f9-ed62dd1def4e.png">
Since for me in obsidian it still looks like this:
![Zrzut ekranu 2023-04-18 o 06 52 15](https://user-images.githubusercontent.com/1098831/232674574-475a136b-1b96-4036-920d-7093e4fc604b.png)
There is a possibility that i screwed config :D

**Reply by sigrunixia** [reply]
@felislynx-silae Do you mean that @jyroger's statblock is looking like that for you, or your own custom one you are trying to make is doing that?

In the case of the later, that is better off in a new thread.

In the case of the former, I opened it and resaved it, just in case. It's now on the freshest build of Fantasy Statblocks. I would also check to make sure you are on the newest install of Obsidian. If you haven't installed Obsidian since December, you will need to download an installer and run it to get some necessary foundation updates. 

[Cyberpunk Red.json.txt](https://github.com/valentine195/fantasy-statblocks/files/11258190/Cyberpunk.Red.json.txt)

Take the .TXT off of the file so that it is a .json. Then import that into Fantasy Statblocks and see if that works. 

````yaml
```statblock
layout: Cyberpunk Red
name: Test
image:
role: Test
role_ability: Test
wound: Test
hp: 100
dice: true
armor:
  - name: Test
    desc: "Test"
weapons:
  - name: Test
    desc: "Test"
gear:
  - name: Test
    desc: "Test"
cyberware:
  - name: Test
    desc: Test
image:
armor_head: Test
armor_body: Test
int: 10
ref: 10
dex: 10
tech: 10
cool: 10
will: 10
move: 10
body: 10
emp: 10
accounting: 1
acting: 1
air_vehicle_tech: 1
animal_handling: 1
archery: 1
athletics: 1
autofire: 1
basic_tech: 1
brawling: 1
bribery: 1
bureaucracy: 1
business: 1
composition: 1
conceal/reveal_object: 1
concentration: 1
contortionist: 1
conversation: 1
criminology: 1
cryptography: 1
cybertech: 1
dance: 1
deduction: 1
demolitions: 1
drive_land_vehicle: 1
education: 1
electronics_-_security_tech: 1
endurance: 1
evasion: 1
first_aid: 1
forgery: 1
gamble: 1
handgun: 1
heavy_weapons: 1
human_perception: 1
interrogation: 1
land_vehicle_tech: 1
language_english: 1
language_streetslang: 1
library_search: 1
lip_reading: 1
local_expert: 1
martial_arts: 1
melee_weapon: 1
paint_draw_sculpt: 1
paramedic: 1
perception: 1
personal_grooming: 1
persuasion: 1
photography_film: 1
pick_lock: 1
pick_pocket: 1
pilot_air_vehicle: 1
pilot_sea_vehicle: 1
play_instrument: 1
resist_torture_drugs: 1
riding: 1
science: 1
sea_vehicle_tech: 1
shoulder_arms: 1
stealth: 1
streetwise: 1
surgery: 1
tactics: 1
tracking: 1
trading: 1
wardrobe_style: 1
weaponstech: 1
wilderness_survival: 1
```
````
