### DISCUSSION TITLE
Dungeon World by @Cosmic-Egg

### DISCUSSION THREAD

**Discussion by sigrunixia** [Obsidian-TTRPG-Community/fantasy-statblocks#162] [Show and tell]
This thread is for @Cosmic-Egg and their Dungeon World Statblock

---

I created a simple Dungeon World Layout based on the layout provided in the sourcebook. 
The fields are:
- name
- tags
- hp (can include roll)
- armor
- attack (can include roll)
- attack_range (optional can just be included in attack string)
- features (optional)
- description (optional, markdown allowed)
- instinct (optional, markdown allowed, I start the string with _Instinct:_ to make it look nicer)

Looks like github won't let me upload a JSON file so I put it in a zip. If people would prefer I can just copy and paste the raw JSON in a comment instead.
[Dungeon World.zip](https://github.com/valentine195/obsidian-5e-statblocks/files/8163021/Dungeon.World.zip)

## Example Monster

```yaml
example monster:

name: Flying Horse
tags: Group, Construct
hp: 10
armor: 2
attack: Sharp Hooves 1 (1d8)
attack_range: Close
features: Wings
description: Don’t go thinking that every creature not natural-born is a horrible abomination. Don’t imagine for a second that they’re all tentacles and screaming and blood or whatever. Take this noble beast, for example. Lovely thing, isn’t it? A fine white horse with the wings of a swan. Don’t look like it ought to be able to fly, but it does. The elves work miracles, in their own way. They breed true—that’s the purity of elf-magic at work. Hatching from little crystal eggs and bonded with their riders for life. There’s still some beauty in the world, mark my words
instinct: _Instinct:_ To carry aloft
```

---

Original Link: https://github.com/valentine195/fantasy-statblocks/discussions/41#discussioncomment-2274554
