### DISCUSSION TITLE
Pathfinder 1e Statblock by @theschabi

### DISCUSSION THREAD

**Discussion by sigrunixia** [Obsidian-TTRPG-Community/fantasy-statblocks#164] [Show and tell]
This thread is for @theschabi's Pathfinder 1e Statblock

---

I made a Layout for Pathfinder 1e based on the statblocks in various books. There are a few things included, thatmost monsters won't need, like tactics.

As I am german and play in german, I made a german and an english version of the layout.

![grafik](https://user-images.githubusercontent.com/108626410/177050492-154c5dc9-a666-45e3-b0e1-0f3cd21cfe44.png)

```yaml
image: [[.png]]
Monster_CR: 
name: 
Monster_XP: 
race: 
class: 
level: 
alignment: 
size: 
type: 
subtype: 

INI: + 
senses: 
aura: 

AK: 
touch: 
flat-footed: 
AK-bonuses: ()

HP: 
HD: 
saves:
- Fort: 
- Ref: 
- Wil: 
immune: 
resist: 
DR: 
defensive_abillities: 
SR: 
weak: 

speed: 
melee: 
damage_mel: 
ranged: 
damage_ran: 
space: 
reach: 
special_attacks: 
spell-like_abilities: 
- name: - 
  desc: - 
- name: -
  desc: - 
- name: -
  desc: -
known_spells:
- name: - 
  desc: - 
- name: -
  desc: - 
- name: -
  desc: -
spells_prepared:
- name: - 
  desc: - 
- name: -
  desc: - 
- name: -
  desc: -


Tactics:
- name: before fighting 
  desc: -
- name: fighting
  desc: - 
- name: moral
  desc: -
- name: base stats
  desc: -
  
p1e_stats: [0, 0, 0, 0, 0, 0]

battlestats:
- name: BAB 
  desc: + 
- name: CMB
  desc: + 
- name: CMD
  desc: 
  
feats:
  - name: -
    desc: -

Acrobatics: 
Appraise: 
Bluff: 
Climb: 
Craft: 
Diplomacy: 
Disable_Device:
Disguise: 
Escape_Artist: 
Fly: 
Handle_Animal: 
Heal: 
Intimidate: 
Knowledge_arcana: 
Knowledge_dungeoneering: 
Knowledge_engineering: 
Knowledge_geography: 
Knowledge_history: 
Knowledge_local: 
Knowledge_nature: 
Knowledge_nobility: 
Knowledge_planes: 
Knowledge_religion: 
Linguistics: 
Perception: 
Perform: 
Profession: 
Ride: 
Sense_Motive:
Sleight_of_Hand: 
Spellcraft: 
Stealth: 
Survival: 
Swim: 
Use_Magic_Device: 

racial_modifiers:
- 
  
languages: 
special_qualities:
battleequipment: 

ecology: 
  - name: Environment
    desc: 
  - name: Organisation
    desc:   
  - name: Treasure
    desc: 

special_abilities:
```
---
[Pathfinder_1e_Layout_DE-theschabi.zip](https://github.com/valentine195/fantasy-statblocks/files/11218878/Pathfinder_1e_Layout_DE-theschabi.zip)
[Pathfinder_1e_Layout_EN-theschabi.zip](https://github.com/valentine195/fantasy-statblocks/files/11218879/Pathfinder_1e_Layout_EN-theschabi.zip)

**Original Thread**: https://github.com/valentine195/fantasy-statblocks/discussions/41#discussioncomment-3073626
