### DISCUSSION TITLE
DnD 3.5 By @Trellinane

### DISCUSSION THREAD

**Discussion by sigrunixia** [Obsidian-TTRPG-Community/fantasy-statblocks#166] [Show and tell]
This thread is for @Trellinane and their Dnd 3.5 Statblock

---

My first attempt at a D&D 3.5e Layout.  It seems to be working so far but its pretty simplisitic.  I may try to make some asthetic changes later.  Let me know if you see any bugs.  

```yaml
name: string
source: string
layout: [D&D 3.5e Layout]
columnWidth: number
image: [[image_name]]
Name: string
Size:  string
Type:  string
Subtype: (string) 
Hit Dice:  num-d-sides
Initiative: number
Speed: string
Armor Class: string
Base Attack/Grapple: numbers
Attack: string
Full Attack: string
Space/Reach: string
Special Attacks: string
Special Qualities: string
spells:
  - Typical Spells Prepared
  - 0 level
  - 1st level
  - 2nd level
  - 3rd level
  - 4th level
  - 5th level
  - 6th level
  - 7th level 
  - 8th level 
  - 9th level 
Saves:
  - Fort: 0
  - Ref: 0
  - Will: 0
Abilities: [0, 0, 0, 0, 0, 0]
Skills:
  - Appraise: 0
  - Autohypnosis: 0
  - Balance: 0
  - Bluff: 0
  - Climb: 0
  - Concentration: 0
  - Control Shape: 0
  - Craft: 0
  - Decipher Script: 0
  - Diplomacy: 0
  - Disable Device: 0
  - Disguise: 0
  - Escape Artist: 0
  - Forgery: 0
  - Gather Information: 0
  - Handle Animal: 0
  - Heal: 0
  - Hide: 0
  - Intimidate: 0
  - Jump: 0
  - Knowledge: 0 
  - Listen: 0
  - Move Silently: 0
  - Open Lock: 0
  - Perform: 0
  - Psicraft: 0
  - Profession: 0
  - Ride: 0
  - Search: 0
  - Sense Motive: 0
  - Sleight of Hand: 0
  - Speak Language: 0
  - Spellcraft: 0
  - Spot: 0
  - Survival: 0
  - Swim: 0
  - Tumble: 0
  - Use Magic Device: 0
  - Use Psionic Device: 0
  - Use Rope: 0
Feats:  string
Environment:  string
Organization: string
Challenge Rating: string
Treasure: string
Alignment: string
Advancement: string
Level Adjustment: string
```

[D&D 3.5e Layout.zip](https://github.com/valentine195/obsidian-5e-statblocks/files/10199053/D.D.3.5e.Layout.zip)

---

**Original Thread**: https://github.com/valentine195/fantasy-statblocks/discussions/41#discussioncomment-4359616
