### DISCUSSION TITLE
Small Headers and uncropped images

### DISCUSSION THREAD

**Discussion by Poetowiec** [Obsidian-TTRPG-Community/fantasy-statblocks#215] [Q&A]
Hi! 

I'm making new layout and have problem with headers and images.
Headers are very small (H1 on screenshot) and images are pointed at center of the image (I don't want to cut it for face only).
Can I change it somehow?

Thanks in advance!
![headers](https://user-images.githubusercontent.com/132654287/236440907-cc9f505b-c37e-4f10-9ea5-a758de88fa48.jpg)

**Comment by sigrunixia** [comment]
> Hi!
> 
> I'm making new layout and have problem with headers and images. Headers are very small (H1 on screenshot) and images are pointed at center of the image (I don't want to cut it for face only). Can I change it somehow?
> 
> Thanks in advance! ![headers](https://user-images.githubusercontent.com/132654287/236440907-cc9f505b-c37e-4f10-9ea5-a758de88fa48.jpg)

Hello!

The header is currently controlled by the default styling of your H1 in a theme. We are working on unbinding this, but in the interim, it can be styled with a CSS snippet.

```scss

.statblock.yourlayouthere .heading {
    font-family: var(--statblock-heading-font);
    font-weight: var(--statblock-heading-font-weight);
    font-variant: var(--statblock-heading-font-variant);
    line-height: var(--statblock-heading-line-height);
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 0px;
    letter-spacing: 1px;
    color: var(--statblock-heading-font-color);
  }

 .statblock.yourlayouthere h1.heading .statblock-heading .YAML-KEY {
    // Your Styles Here
  }

```

The YAML-Key would be whatever you named the H1 block in the layout editor.

Similarly, fixing the token image can be done with a css snippet. 

```css
.statblock.yourlayoutnamehere .image img {
    object-position: center top;
}
```
