### DISCUSSION TITLE
Shadorwun Anarchy

### DISCUSSION THREAD

**Discussion by Dramac** [Obsidian-TTRPG-Community/fantasy-statblocks#235] [Show and tell]
I made a first layout for shadowrun Anarchy, both in french and english

[Shadowrun Anarchy](https://acloud7.zaclys.com/index.php/s/5zECALa4338ziWC)
Exemple :

```
layout: Shadowrun_EN
name: Kathryn Mac-Neel
metatype: human
concept: sarariwoman
description: 29 year's old, pretty, classy, white top and skirt, blue sunglasses
stats: [2, 4, 5, 5, 4, 3]
def: 9
armor: 6
monitor: 9/11
skills: Bargain 6 (2+C), Sports 6 (2+A), Fire weapon 6 (2+A)
shadow:
 - name: optimised pheromone
   desc: Bioware, 2D on CHA tests
 - name: Datajack
   desc: matrix connection
weapons: [Fischetti security, Ok, -2, -]

```

![Image](https://user-images.githubusercontent.com/942075/185789053-1b674943-931d-4bc1-ad74-cc00751f47c7.png)

Sorry for the firsts to try it. I shared the wrong link.
There is a screen capture for the details of the structure.
