### DISCUSSION TITLE
Layouts!

### DISCUSSION THREAD

**Discussion by valentine195** [Obsidian-TTRPG-Community/fantasy-statblocks#41] [Show and tell]
Hello everyone!

I thought this was area likely to be the best place to share custom layouts that you have built. Feel free to post a thread with your custom layout.

Your custom layouts can be exported by hitting the export button from within Fantasy Statblocks settings. If you have any custom CSS, please include that as well. 

---

Note from @sigrunixia:
Please confirm that the licensing and publishing of the statblock you are making allows you to publicly post it. There are some publishers that specifically prohibit sharing of exact styles and trade dress.

**Comment by Syrkres** [comment]
When you say custom layouts I assume templates? I was thinking of doing a similar thing for the NPC building I was working on where users could use/add alternate templates.

**Reply by valentine195** [reply]
Basically, yep! You can create custom layouts in settings, then define which layout you want a statblock to use to render.

**Comment by Duke-Igthorn** [comment]
I'm working on remodeling the 5e template into something that would work with AGE based games like Fantasy AGE.
Looking very much forward to an easy im-/export function. :)

**Comment by Cosmic-Egg** [comment]
I created a simple Dungeon World Layout based on the layout provided in the sourcebook. 
The fields are:
- name
- tags
- hp (can include roll)
- armor
- attack (can include roll)
- attack_range (optional can just be included in attack string)
- features (optional)
- description (optional, markdown allowed)
- instinct (optional, markdown allowed, I start the string with _Instinct:_ to make it look nicer)

Looks like github won't let me upload a JSON file so I put it in a zip. If people would prefer I can just copy and paste the raw JSON in a comment instead.
[Dungeon World.zip](https://github.com/valentine195/obsidian-5e-statblocks/files/8163021/Dungeon.World.zip)

**Reply by Cosmic-Egg** [reply]
example monster:

name: Flying Horse
tags: Group, Construct
hp: 10
armor: 2
attack: Sharp Hooves 1 (1d8)
attack_range: Close
features: Wings
description: Don’t go thinking that every creature not natural-born is a horrible abomination. Don’t imagine for a second that they’re all tentacles and screaming and blood or whatever. Take this noble beast, for example. Lovely thing, isn’t it? A fine white horse with the wings of a swan. Don’t look like it ought to be able to fly, but it does. The elves work miracles, in their own way. They breed true—that’s the purity of elf-magic at work. Hatching from little crystal eggs and bonded with their riders for life. There’s still some beauty in the world, mark my words
instinct: \_Instinct:_ To carry aloft

**Reply by sigrunixia** [reply]
Hello, in order to help individuals find information better andas a part of a larger documentation project, this thread is being split up.

Your new thread is here: https://github.com/valentine195/fantasy-statblocks/discussions/162#discussion-5081439

**Comment by Greven145** [comment]
I wanted a very compact view of my character that I could just keep in a vertical stack in a vertically split pane. The stats are still a little big I think.


The JSON for the template and a sample statblock with preview below.

```json
{"blocks":[{"type":"group","id":"99293949a878","properties":[],"nested":[{"type":"inline","id":"5ae9bbd85bda","properties":[],"hasRule":false,"nested":[{"type":"group","id":"b8d989194829","properties":[],"nested":[{"type":"heading","id":"6a4818784999","properties":["name"],"fallback":"-","conditioned":true},{"type":"subheading","id":"19788b1b8a4b","properties":["race","subtype","class","alignment"],"conditioned":true},{"type":"property","id":"c9f81beaa978","properties":[],"fallback":"-","callback":"let output = \"\";\nlet icons = {\n\t\"ac\": 0x26E8,\n\t\"hp\": 0x1F5A4,\n\t\"speed\": 0x1F97E,\n\t\"Perception\": 0x1F440,\n\t\"Investigation\": 0x1F50E,\n\t\"Insight\": 0x1F4A1,\n}\nlet statWithIcon = (targetStat, substat) => {\n\tif (targetStat == undefined || targetStat in monster === false) {\n\t\treturn \"\";\n\t}\n\t\n\tlet stat = monster[targetStat];\n\tlet icon = icons[targetStat];\n\tif ( substat !== undefined && substat in stat ){\n\t\tstat = stat[substat];\n\t\ticon = icons[substat];\n\t}\n\treturn `${String.fromCodePoint(icon)}${stat} `;\n}\noutput += statWithIcon(\"ac\");\noutput += statWithIcon(\"hp\");\noutput += statWithIcon(\"speed\");\noutput += statWithIcon(\"passives\", \"Perception\");\noutput += statWithIcon(\"passives\", \"Investigation\");\noutput += statWithIcon(\"passives\", \"Insight\");\nreturn output.trim();","display":" "}]},{"type":"image","id":"3bba8b8b0849","properties":["image"],"fallback":"-","conditioned":true}]},{"type":"property","id":"eb590b794afa","properties":[""],"fallback":"-","callback":"let getMod = (statVal) => {\n  let mod = Math.floor(((statVal ?? 10) - 10) / 2);\n  return `${mod > 0 ? \"+\" : mod < 0 ? \"-\" : \"\"}${Math.abs(mod)}`;\n}\n\nlet output = \"\";\nlet labels = [\"Str\",\"Dex\",\"Con\",\"Int\",\"Wis\",\"Cha\"];\nif (\"stats\" in monster) {\n  let stats = monster.stats;\n  for ( let x = 0; x < stats.length; x++){\n    let stat = stats[x];\n    let label = labels[x];\n    let mod = getMod(stat);\n    output += `${label}: ${stat} (${mod}) `;\n  }\n  return output.trim();\n}\nreturn \"\";","conditioned":false,"display":" ","markdown":false,"dice":false}]},{"type":"inline","id":"28dbfa9a199b","properties":[],"nested":[{"type":"saves","id":"684a1878690a","properties":["saves"],"fallback":"-","conditioned":true},{"type":"property","id":"e81b68d87929","properties":["damage_immunities"],"fallback":"-","display":"Immun","conditioned":true},{"type":"property","id":"799a6b18598a","properties":["condition_immunities"],"fallback":"-","display":" ","conditioned":true},{"type":"property","id":"6b4a1b2af8d9","properties":["damage_resistances"],"fallback":"-","display":"Resist","conditioned":true},{"type":"property","id":"49eab86929fb","properties":["damage_vulnerabilities"],"fallback":"-","display":"Vuln","conditioned":true}]},{"type":"inline","id":"696aea68d918","properties":[],"nested":[{"type":"property","id":"5ba93b3bdbdb","properties":["languages"],"fallback":"-","display":"Languages","conditioned":true},{"type":"property","id":"5b0a98581ae9","properties":["senses"],"fallback":"-","display":"Senses","conditioned":true}]}],"name":"Player"}
```

``` yml
name: Narnaar
layout: Player
image: [[default-avatar-builder.png]]
size: Medium
race: Chromatic Dragonborn
subtype: Way of Mercy Monk
alignment: Neutral Good
ac: 18
hp: 51
speed: 55
stats: [10,20,13,8,16,10]
saves:
  - Str: 3
  - Dex: 8
  - Con: 1
  - Int: -1
  - Wis: 1
  - Cha: 0
damage_resistances: Acid
languages: Common, Draconic, Dwarvish
passives:
  Perception: 16
  Investigation: 9
  Insight: 16
```

![Narnaar](https://user-images.githubusercontent.com/746356/157807952-64370212-62d3-45ee-b08c-5cc8d40b999f.png)

**Reply by sigrunixia** [reply]
Hello, in order to help individuals find information better andas a part of a larger documentation project, this thread is being split up.

Your new thread is here: https://github.com/valentine195/fantasy-statblocks/discussions/163#discussion-5081453

**Comment by theschabi** [comment]
I made a Layout for Pathfinder 1e based on the statblocks in various books. There are a few things included, thatmost monsters won't need, like tactics.
As I am german and play in german, I made a german and an english version of the layout.

[Pathfinder_1e_Layout_DE.zip](https://github.com/valentine195/fantasy-statblocks/files/10833847/Pathfinder_1e_Layout_DE.zip)
[Pathfinder_1e_Layout_EN.zip](https://github.com/valentine195/fantasy-statblocks/files/10833848/Pathfinder_1e_Layout_EN.zip)


![grafik](https://user-images.githubusercontent.com/108626410/177050492-154c5dc9-a666-45e3-b0e1-0f3cd21cfe44.png)

```

image: [[.png]]
Monster_CR: 
name: 
Monster_XP: 
race: 
class: 
level: 
alignment: 
size: 
type: 
subtype: 

INI: + 
senses: 
aura: 

AK: 
touch: 
flat-footed: 
AK-bonuses: ()

HP: 
HD: 
saves:
- Fort: 
- Ref: 
- Wil: 
immune: 
resist: 
DR: 
defensive_abillities: 
SR: 
weak: 

speed: 
melee: 
damage_mel: 
ranged: 
damage_ran: 
space: 
reach: 
special_attacks: 
spell-like_abilities: 
- name: - 
  desc: - 
- name: -
  desc: - 
- name: -
  desc: -
known_spells:
- name: - 
  desc: - 
- name: -
  desc: - 
- name: -
  desc: -
spells_prepared:
- name: - 
  desc: - 
- name: -
  desc: - 
- name: -
  desc: -


Tactics:
- name: before fighting 
  desc: -
- name: fighting
  desc: - 
- name: moral
  desc: -
- name: base stats
  desc: -
  
p1e_stats: [0, 0, 0, 0, 0, 0]

battlestats:
- name: BAB 
  desc: + 
- name: CMB
  desc: + 
- name: CMD
  desc: 
  
feats:
  - name: -
    desc: -

Acrobatics: 
Appraise: 
Bluff: 
Climb: 
Craft: 
Diplomacy: 
Disable_Device:
Disguise: 
Escape_Artist: 
Fly: 
Handle_Animal: 
Heal: 
Intimidate: 
Knowledge_arcana: 
Knowledge_dungeoneering: 
Knowledge_engineering: 
Knowledge_geography: 
Knowledge_history: 
Knowledge_local: 
Knowledge_nature: 
Knowledge_nobility: 
Knowledge_planes: 
Knowledge_religion: 
Linguistics: 
Perception: 
Perform: 
Profession: 
Ride: 
Sense_Motive:
Sleight_of_Hand: 
Spellcraft: 
Stealth: 
Survival: 
Swim: 
Use_Magic_Device: 

racial_modifiers:
- 
  
languages: 
special_qualities:
battleequipment: 

ecology: 
  - name: Environment
    desc: 
  - name: Organisation
    desc:   
  - name: Treasure
    desc: 

special_abilities:

```
