### DISCUSSION TITLE
Symbaroum Statblock

### DISCUSSION THREAD

**Discussion by voncotta** [Obsidian-TTRPG-Community/fantasy-statblocks#91] [Q&A]
Love your work.

Would it be possible to tweak the code to produce a statblock for the Symbaroum ttrpg system?
I have no coding skills, but would be happy to contribute.

Cheers.

**Comment by sigrunixia** [comment]
Hi @voncotta.

This can produce many forms of statblocks. It just depends how much effort and time you want to put into it. 

Are you still interested?

**Comment by Ogolar** [comment]
Hi @voncotta,
Maybe this will help?

I did´t two different on. I´m form germany, so the text is in german.
The differenc is the layout of the defence, armor, tougness und pain threshold

The **first option** looks like this
![Raufbold01](https://github.com/javalent/fantasy-statblocks/assets/3579484/062c8d4a-7073-402e-8e78-38584ceb09be)

Use this YAML

```
# Layout to use
layout: Symbaroum
# Name of the creature
name: Raufbold
# Personality/ Zitat
flavour-text: „Kommt schon! Nehmt das, und da…“
# Picture insert with Markdown
image: 
# Größe
size: 1,88 m
# Infos
description: Eine Gruppe von Männern und Frauen, die im Leben bisher nicht so viel Glück hatten und glauben, das große Los gezogen zu haben, da ihre Opfer ihnen zahlenmäßig stark unterlegen sind. Sie sind davon überzeugt, recht erfahren und fähig zu sein, nachdem sie ein paar Reisen in den lichten Davokar unternommen haben, sind den Abenteurern aber vermutlich in keiner Weise gewachsen. Auftreten Geben sich selbstsicher, haben aber in Wahrheit Angst
# Manner
manner: Geben sich selbstsicher, haben aber in Wahrheit Angst
# race = Type of the Creature: Beast, Abomination, Undead, Cultural Being
race: Mensch (Ambrier) 
# Herausforderung/ Resistance (Challenge Rating)
chal-rate: Gering
# Traits
traits: 
 - name: Kontakte
   desc: (Schatzsucher)
# Die Attribute in Englsich
eng_stats: [13 (−3), 5 (+5), 10 (0), 9 (+1), 10 (0), 7 (+3), 11 (−1), 15 (−5)]
# Abilities
abilities: 
 - name: [[Witchsight]]
   desc: (Novice)
 - name: [[Bend Will]]
   desc: (Adept)
# Weapons 
weapon: 
 - name: Speer
   desc: 4 (Lang)
 - name: Bogen
   desc: 4
# Defence, Armor, Tougness, Pain Threshold for Symbaroum 1 or only defence for Symbaroum 2
def: [+2, 2 (Lederrüstung), 11, 7]
# Equipment
items:
 - name: 1W6 Orteg
   desc:
 - name: 2 Thaler
   desc:
# shadow
shadow: Glänzendes Kupfer wie bei einem frisch gefertigten Kessel (Korruption 0)
# Tactics
tactics: Die Raufbolde haben keine besondere Taktik, außer dass sie sich eben in Speerträger und Bogenschützen aufgeteilt haben. Sobald die Hälfte gefallen ist, ergreift der Rest die Flucht.
# Language
languages:
# - name:

```

The JSON-File "Symbaroum"
[Symbaroum.zip](https://github.com/javalent/fantasy-statblocks/files/12244325/Symbaroum.zip)

The **second option** looks like this
![Raufbold02](https://github.com/javalent/fantasy-statblocks/assets/3579484/9f546d42-f75a-483e-ae12-c7d9995d7989)

The YAML

```
# Zu verwendendes Layout
layout: Symbaroum
# Name der Kreatur oder des Charakter
name: Raufbold
# Personality/ Zitat
flavour-text: „Kommt schon! Nehmt das, und da…“
# Bild
image: 
# Größe
size: 1,88 m
# Infos
description: Eine Gruppe von Männern und Frauen, die im Leben bisher nicht so viel Glück hatten und glauben, das große Los gezogen zu haben, da ihre Opfer ihnen zahlenmäßig stark unterlegen sind. Sie sind davon überzeugt, recht erfahren und fähig zu sein, nachdem sie ein paar Reisen in den lichten Davokar unternommen haben, sind den Abenteurern aber vermutlich in keiner Weise gewachsen. Auftreten Geben sich selbstsicher, haben aber in Wahrheit Angst
# Manner/ Auftreten
manner: Geben sich selbstsicher, haben aber in Wahrheit Angst
# race/ Rasse = Type of the Creature: Beast, Abomination, Undead, Cultural Being
race: Mensch (Ambrier) 
# Herausforderung/ Resistance (Challenge Rating)
chal-rate: Gering
# Traits/ Merkmale
traits: 
 - name: Kontakte
   desc: (Schatzsucher)

# Die Attribute in Englsich
eng_stats: [13 (−3), 5 (+5), 10 (0), 9 (+1), 10 (0), 7 (+3), 11 (−1), 15 (−5)]

# Abilities /Fähigkeiten
abilities: 
 - name: [[Witchsight]]
   desc: (Novice)
 - name: [[Bend Will]]
   desc: (Adept)
# Weapons /Waffen
weapon: 
 - name: Speer
   desc: 4 (Lang)
 - name: Bogen
   desc: 4
# Armor/ Rüstung
ac: 2 (Lederrüstung)
# Defence/ Vereteidiung, 
def: +2
# Toughness/ Zähigkeit
tough: 11
# Pain Threshold / Schmerzgrenze
pain: 7
# Equipment /Ausrüstung
items:
 - name: 1W6 Orteg
   desc:
 - name: 2 Thaler
   desc:
# shadow /Schatten
shadow: Glänzendes Kupfer wie bei einem frisch gefertigten Kessel (Korruption 0)
# Tactics/ Taktik
tactics: Die Raufbolde haben keine besondere Taktik, außer dass sie sich eben in Speerträger und Bogenschützen aufgeteilt haben. Sobald die Hälfte gefallen ist, ergreift der Rest die Flucht.
# Language /Sprachen
languages:
# - name:
```


The JSON-File "Symbaroum2"
[Symbaroum2.zip](https://github.com/javalent/fantasy-statblocks/files/12244339/Symbaroum2.zip)
